Fixed mafft libexec inclusion.

diff --git a/include/bin/mafft b/include/bin/mafft
--- a/include/bin/mafft
+++ b/include/bin/mafft
@@ -1,7 +1,7 @@
 #! /bin/bash 
 er=0;
 myself=`dirname "$0"`/`basename "$0"`; export myself
-version="v7.490 (2021/Oct/30)"; export version
+version="v7.505 (2022/Apr/10)"; export version
 LANG=C; export LANG
 os=`uname`
 progname=`basename "$0"`
@@ -36,7 +36,9 @@ fi
 if [ "$MAFFT_BINARIES" ]; then
 	prefix="$MAFFT_BINARIES"
 else
-	prefix=/home/freeda/miniconda3/envs/included/libexec/mafft
+	echo "" 1>&2
+	echo "ERROR: MAFFT_BINARIES environment variable not assigned." 1>&2
+	exit 1
 fi
 export prefix # iranai
 
@@ -252,12 +254,15 @@ strdir="$PWD"
 scorematrix="/dev/null"
 textmatrix="/dev/null"
 treeinfile="/dev/null"
+codonposfile="/dev/null"
+codonscorefile="/dev/null"
 rnascoremtx=" "
 laraparams="/dev/null"
 foldalignopt=" "
 treealg=" -X 0.1 "
 sueff="1.0"
 maxambiguous="1.0"
+dofilter=0
 scoreoutarg=" "
 numthreads=0
 numthreadsit=-1
@@ -410,6 +415,25 @@ if [ $# -gt 0 ]; then
 		elif [ "$1" = "--maxambiguous" ]; then
 			shift   
 			maxambiguous="$1"
+			dofilter=1
+		elif [ "$1" = "--codonpos" ]; then
+			shift   
+			codonposfile="$1"
+			if [ ! -e "$codonposfile" ]; then
+				echo "Cannot open $codonposfile" 1>&2
+				echo "" 1>&2
+				exit
+			fi
+			codonposopt=" -R "
+		elif [ "$1" = "--codonscore" ]; then
+			shift   
+			codonscorefile="$1"
+			if [ ! -e "$codonscorefile" ]; then
+				echo "Cannot open $codonscorefile" 1>&2
+				echo "" 1>&2
+				exit
+			fi
+			codonscoreopt=" -S "
 		elif [ "$1" = "--noscore" ]; then
 			scorecalcopt=" -Z "
 		elif [ "$1" = "--6mermultipair" ]; then
@@ -645,10 +669,21 @@ if [ $# -gt 0 ]; then
 			addarg0="-K -I"
 			addfile="$1"
 			fragment=-2
+		elif [ "$1" = "--addtotop" ]; then 
+			shift   
+			addarg0="-K -I"
+			addfile="$1"
+			fragment=-3
 		elif [ "$1" = "--smoothing" ]; then 
 			add2ndhalfarg=$add2ndhalfarg" -p "
 		elif [ "$1" = "--keeplength" ]; then 
 			add2ndhalfarg=$add2ndhalfarg" -Y "
+		elif [ "$1" = "--compactmapout" ]; then 
+			add2ndhalfarg=$add2ndhalfarg" -z -Y "
+		elif [ "$1" = "--compactmapoutfile" ]; then 
+			shift
+			add2ndhalfarg=$add2ndhalfarg" -z -Y "
+			mapoutfile="$1"
 		elif [ "$1" = "--mapout" ]; then 
 			add2ndhalfarg=$add2ndhalfarg" -Z -Y "
 		elif [ "$1" = "--mapoutfile" ]; then 
@@ -1079,9 +1114,9 @@ function removetmpfile() { # for MPI
 			echo ""                             >> "$TMPFILE/infile"
 			cat "$addfile"        | tr "\r" "\n" | grep -v "^$" > "$TMPFILE/_addfile"
 
-			if [ $maxambiguous != "1.0" ]; then
-				mv "$TMPFILE/infile" "$TMPFILE/_tofilter"
-				"$prefix/filter" -m $maxambiguous $seqtype -i "$TMPFILE/_tofilter" > "$TMPFILE/infile" 2>>"$progressfile" || exit 1
+			if [ $dofilter -eq 1 ]; then
+#				mv "$TMPFILE/infile" "$TMPFILE/_tofilter"
+#				"$prefix/filter" -m $maxambiguous $seqtype -i "$TMPFILE/_tofilter" > "$TMPFILE/infile" 2>>"$progressfile" || exit 1
 				mv "$TMPFILE/_addfile" "$TMPFILE/_tofilter"
 				"$prefix/filter" -m $maxambiguous $seqtype -i "$TMPFILE/_tofilter" > "$TMPFILE/_addfile" 2>>"$progressfile" || exit 1
 			fi
@@ -1090,6 +1125,8 @@ function removetmpfile() { # for MPI
 			cat "$scorematrix"    | tr "\r" "\n" | grep -v "^$" > "$TMPFILE/_aamtx"
 			cat "$mergetable"     | tr "\r" "\n" | grep -v "^$" > "$TMPFILE/_subalignmentstable"
 			cat "$treeinfile"     | tr "\r" "\n" | grep -v "^$" > "$TMPFILE/_guidetree"
+			cat "$codonposfile"   | tr "\r" "\n" | grep -v "^$" > "$TMPFILE/_codonpos"
+			cat "$codonscorefile" | tr "\r" "\n" | grep -v "^$" > "$TMPFILE/_codonscore"
 			cat "$seedtablefile"  | tr "\r" "\n" | grep -v "^$" > "$TMPFILE/_seedtablefile"
 			cat "$laraparams"     | tr "\r" "\n" | grep -v "^$" > "$TMPFILE/_lara.params"
 			cat "$pdblist"        | tr "\r" "\n" | grep -v "^$" > "$TMPFILE/pdblist"
@@ -1104,6 +1141,8 @@ $addfile
 $scorematrix
 $mergetable
 $treeinfile
+$codonposfile
+$codonscorefile
 $seedtablefile
 $laraparams
 $pdblist
@@ -1335,10 +1374,11 @@ $ownlist"
 				exit 1;
 			fi
 # nagasa check!
-#
-			if [ $npair -gt 10000000 -o $nlen -gt 5000 ]; then  # 2017/Oct 
+#			if [ $npair -gt 10000000 -o $nlen -gt 5000 ]; then  # 2017/Oct 
+			if [ $npair -gt 10000000 -o $nlen -gt 5000 -o $nadd -gt 500000 ]; then  # 2021/Dec pairlocalalign to buntan
 				distance="ktuples"
 				echo "use ktuples, size=$tuplesize!" 1>>"$progressfile"
+#			elif [ $npair -gt 3000000 -o $nlen -gt 5000 ]; then  # 2017/Oct
 			elif [ $npair -gt 3000000 -o $nlen -gt 5000 ]; then  # 2017/Oct
 				distance="multi"
 				weighti="0.0"
@@ -2000,6 +2040,11 @@ $ownlist"
 			laof=0.0               # 2015Jun01
 			lexp=0.0               # 2015Jun01
 			iterate=0
+		elif [ $fragment -eq "-3" ]; then
+			addarg="$addarg0 $nadd"
+			addsinglearg="-x"       # add to top, 2021/12/31
+			cycle=1 # chuui 2014Aug25
+			iterate=0
 		else
 			addarg="$addarg0 $nadd"
 			addsinglearg=""
@@ -2027,6 +2072,21 @@ $ownlist"
 			echo '' 1>>"$progressfile"
 			echo 'The --keeplength and --mapout options are supported' 1>>"$progressfile"
 			echo 'only with --add, --addfragments or --addlong.' 1>>"$progressfile"
+			echo '' 1>>"$progressfile"
+			exit 1
+		fi
+	fi
+
+	if [ "$codonposfile" != "/dev/null" -o "$codonscorefile" != "/dev/null" ]; then
+		if [ $nadd -eq "0" -o $fragment -eq "0" ]; then
+			echo '' 1>>"$progressfile"
+			echo "'--codonpos' and '--codonscore' options are supported only with the '--6merpair --addfragments' option." 1>>"$progressfile"
+			echo '' 1>>"$progressfile"
+			exit 1
+		fi
+		if [ $distance != "ktuples" ]; then # ato de taiou
+			echo '' 1>>"$progressfile"
+			echo "'--codonpos' and '--codonscore' options are supported only with the '--6merpair --addfragments' option, at this point." 1>>"$progressfile"
 			echo '' 1>>"$progressfile"
 			exit 1
 		fi
@@ -2143,6 +2203,8 @@ $ownlist"
 		strategy=$strategy"full"
 	elif [ $fragment -eq -2 ]; then
 		strategy=$strategy"long"
+	elif [ $fragment -eq -3 ]; then
+		strategy=$strategy"top"
 	else
 		strategy=$strategy$cycle
 	fi
@@ -2502,7 +2564,7 @@ $ownlist"
 				"$prefix/pairlocalalign" $localparam $addarg   -C $numthreads $seqtype $model  -g $lexp -f $lgop -Q $spfactor -h $laof -L $usenaivepairscore < infile > /dev/null  2>>"$progressfile"      || exit 1
 				cat hat3.seed hat3 > hatx
 				mv hatx hat3
-				"$prefix/addsingle" -Q 100 $legacygapopt -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg $scoreoutarg < infile   > /dev/null 2>>"$progressfile" || exit 1
+				"$prefix/addsingle" $codonposopt $codonscoreopt -Q 100 $legacygapopt -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg  < infile   > /dev/null 2>>"$progressfile" || exit 1
 			else
 				"$prefix/tbfast" _  -u $unalignlevel $localparam -C $numthreads $seqtype $model  -g $lexp -f $lgop -Q $spfactor -h $laof -L $usenaivepairscore $focusarg _ -+ $iterate -W $minimumweight -V "-"$gopdist -s $unalignlevel $legacygapopt $mergearg $termgapopt $outnum $addarg $add2ndhalfarg -C $numthreadstb $rnaopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop -Q $spfactor -h $aof  $param_fft $localparam   $algopt $treealg $scoreoutarg $focusarg < infile   > /dev/null 2>>"$progressfile" || exit 1
 			fi
@@ -2518,7 +2580,7 @@ $ownlist"
 				"$prefix/pairlocalalign" $addarg   -C $numthreads $seqtype $model -e $last_e -w $last_m -g $lexp -f $lgop -Q $spfactor -h $laof -R $last_subopt $last_once -d "$prefix" < infile > /dev/null  2>>"$progressfile"      || exit 1
 				cat hat3.seed hat3 > hatx
 				mv hatx hat3
-				"$prefix/addsingle" -Q 100 $legacygapopt -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg $scoreoutarg < infile   > /dev/null 2>>"$progressfile" || exit 1
+				"$prefix/addsingle" $codonposopt $codonscoreopt -Q 100 $legacygapopt -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg < infile   > /dev/null 2>>"$progressfile" || exit 1
 			else
 				"$prefix/pairlocalalign" -C $numthreads $seqtype $model -e $last_e -w $last_m -g $lexp -f $lgop -Q $spfactor -h $laof -R $last_subopt $last_once -d "$prefix" < infile > /dev/null  2>>"$progressfile"      || exit 1
 #				addarg wo watasanai
@@ -2534,7 +2596,7 @@ $ownlist"
 			mv hat2 hat2n
 			mv hatx hat3
 			if [ $fragment -ne 0 ]; then 
-				"$prefix/addsingle" -Q 100 $legacygapopt -d -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg $scoreoutarg < infile   > /dev/null 2>>"$progressfile" || exit 1
+				"$prefix/addsingle" $codonposopt $codonscoreopt -Q 100 $legacygapopt -d -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg < infile   > /dev/null 2>>"$progressfile" || exit 1
 			else
 				echo "Impossible" 1>&2
 				exit 1
@@ -2547,7 +2609,7 @@ $ownlist"
 			mv hat2 hat2n
 			mv hatx hat3
 			if [ $fragment -ne 0 ]; then 
-				"$prefix/addsingle" -Q 100 $legacygapopt -d -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg $scoreoutarg < infile   > /dev/null 2>>"$progressfile" || exit 1
+				"$prefix/addsingle" $codonposopt $codonscoreopt -Q 100 $legacygapopt -d -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg < infile   > /dev/null 2>>"$progressfile" || exit 1
 			else
 				echo "Impossible" 1>&2
 				exit 1
@@ -2558,7 +2620,7 @@ $ownlist"
 			mv hatx hat3
 			"$prefix/disttbfast" -E 1 -s $unalignlevel $legacygapopt -W $tuplesize $termgapopt $outnum $addarg $add2ndhalfarg -C $numthreads-$numthreadstb $memopt $weightopt $treeinopt $treeoutopt -T -y $seqtype $model -f "-"$gop -Q $spfactor -h $aof  $param_fft $algopt $treealg $scoreoutarg < infile   > /dev/null 2>>"$progressfile" || exit 1
 			if [ $fragment -ne 0 ]; then 
-				"$prefix/addsingle" -Q 100 $legacygapopt -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg $scoreoutarg < infile   > /dev/null 2>>"$progressfile" || exit 1
+				"$prefix/addsingle" $codonposopt $codonscoreopt -Q 100 $legacygapopt -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg < infile   > /dev/null 2>>"$progressfile" || exit 1
 			else
 				"$prefix/tbfast" -W $minimumweight -V "-"$gopdist -s $unalignlevel $legacygapopt $mergearg $termgapopt $outnum $addarg $add2ndhalfarg -C $numthreadstb $rnaopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop -Q $spfactor -h $aof  $param_fft $localparam   $algopt $treealg $scoreoutarg < infile   > /dev/null 2>>"$progressfile" || exit 1
 			fi
@@ -2574,15 +2636,15 @@ $ownlist"
 #			"$prefix/disttbfast" -E 1 -s $unalignlevel $legacygapopt -W $tuplesize $termgapopt $outnum $addarg $add2ndhalfarg -C $numthreads-$numthreadstb $memopt $weightopt $treeinopt $treeoutopt -T -y $seqtype $model -f "-"$gop -Q $spfactor -h $aof  $param_fft $algopt $treealg $scoreoutarg < infile   > /dev/null 2>>"$progressfile" || exit 1
 #			mv hat2 hat2n
 			if [ $fragment -ne 0 ]; then 
-				"$prefix/addsingle" -Q 100 $legacygapopt -d -W $tuplesize -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg $scoreoutarg < infile   > /dev/null 2>>"$progressfile" || exit 1
-#				"$prefix/addsingle" -Q 100 $legacygapopt -d -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg $scoreoutarg < infile   > /dev/null 2>>"$progressfile" || exit 1
+				"$prefix/addsingle" $codonposopt $codonscoreopt -Q 100 $legacygapopt -d -W $tuplesize -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg < infile   > /dev/null 2>>"$progressfile" || exit 1
+#				"$prefix/addsingle" -Q 100 $legacygapopt -d -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg < infile   > /dev/null 2>>"$progressfile" || exit 1
 			else
 				echo "Impossible" 1>&2
 				exit 1
 			fi
 		else
 			if [ $fragment -ne 0 ]; then 
-				"$prefix/addsingle" -Q 100 $legacygapopt -W $tuplesize -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg $scoreoutarg < infile   > /dev/null 2>>"$progressfile" || exit 1
+				"$prefix/addsingle" $codonposopt $codonscoreopt -Q 100 $legacygapopt -W $tuplesize -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop  -h $aof  $param_fft $localparam   $algopt $treealg < infile   > /dev/null 2>>"$progressfile" || exit 1
 			else
 				"$prefix/disttbfast" -q $npickup -E $cycledisttbfast -V "-"$gopdist  -s $unalignlevel $legacygapopt $mergearg -W $tuplesize $termgapopt $outnum $addarg $add2ndhalfarg -C $numthreads-$numthreadstb $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -g $gexp -f "-"$gop -Q $spfactor -h $aof  $param_fft $algopt $treealg $scoreoutarg $anchoropt -x $maxanchorseparation $oneiterationopt < infile   > pre 2>>"$progressfile" || exit 1
 				mv hat3.seed hat3
